
package broker.jproxy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSSecurityUsernameServiceSoap", targetNamespace = "http://stockservice.contoso.com/wse/samples/2005/10")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSSecurityUsernameServiceSoap {


    /**
     * 
     * @param symbols
     * @return
     *     returns java.util.List<broker.jproxy.StockQuote>
     */
    @WebMethod(operationName = "StockQuoteRequest", action = "http://stockservice.contoso.com/wse/samples/2005/10/StockQuoteRequest")
    @WebResult(name = "StockQuote", targetNamespace = "http://stockservice.contoso.com/wse/samples/2005/10")
    @RequestWrapper(localName = "StockQuoteRequest", targetNamespace = "http://stockservice.contoso.com/wse/samples/2005/10", className = "broker.jproxy.StockQuoteRequest")
    @ResponseWrapper(localName = "StockQuotes", targetNamespace = "http://stockservice.contoso.com/wse/samples/2005/10", className = "broker.jproxy.StockQuotes")
    public List<StockQuote> stockQuoteRequest(
        @WebParam(name = "symbols", targetNamespace = "http://stockservice.contoso.com/wse/samples/2005/10")
        ArrayOfString symbols);

}
